### ISSUE TITLE
Missing peer

### ISSUE THREAD

**Issue by Blackbaud-DanHamlin** [jamestalmage/grunt-bower-install-task#2]
![image](https://cloud.githubusercontent.com/assets/11943543/10620394/6fde9c6c-7740-11e5-877e-58c4979b973d.png)

I'm rather stumped as to why this is happening. Any thoughts?  I run npm install and it says bower is missing, but bower -v clearly indicates that bower is present.

**Comment by jamestalmage** [comment]
Install bower locally, not globally

**Comment by jamestalmage** [comment]
Post the full error output

**Comment by Blackbaud-DanHamlin** [comment]
installing locally worked. I don't recall having had to do that in the past. thanks for the input.
